# contains the queries that I am using to test the rag chains
# Define what should be exported from this module
__all__ = [
    'title_query',
    'inclusion_query',
    'exclusion_query',
    'specific_exclusion_query'
]
def title_query(rag_chains):
    print("TITLE QUERY")
    print("=" * 50)
    print(rag_chains["rag_chain_1_chunk1000_overlap100"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_2_chunk1000_overlap200"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_3_chunk1000_overlap300"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_4_chunk1000_overlap400"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_5_chunk1000_overlap500"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_6_chunk2000_overlap100"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_7_chunk2000_overlap200"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_8_chunk2000_overlap300"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_9_chunk2000_overlap400"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_10_chunk2000_overlap500"]["chain"].invoke({"question": "What is the title of the protocol?"}))
    print("=" * 50)

def inclusion_query(rag_chains):
    print("INCLUSION CRITERIA QUERY")
    print("=" * 50)
    print(rag_chains["rag_chain_1_chunk1000_overlap100"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_2_chunk1000_overlap200"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_3_chunk1000_overlap300"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_4_chunk1000_overlap400"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_5_chunk1000_overlap500"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_6_chunk2000_overlap100"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_7_chunk2000_overlap200"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_8_chunk2000_overlap300"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_9_chunk2000_overlap400"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_10_chunk2000_overlap500"]["chain"].invoke({"question": "What are the inclusion criteria of the protocol?"}))
    print("=" * 50)

def exclusion_query(rag_chains):
    print("EXCLUSION CRITERIA QUERY")
    print("=" * 50)
    print(rag_chains["rag_chain_1_chunk1000_overlap100"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_2_chunk1000_overlap200"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_3_chunk1000_overlap300"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_4_chunk1000_overlap400"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_5_chunk1000_overlap500"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_6_chunk2000_overlap100"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_7_chunk2000_overlap200"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_8_chunk2000_overlap300"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_9_chunk2000_overlap400"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_10_chunk2000_overlap500"]["chain"].invoke({"question": "What are the exclusion criteria of the protocol?"}))
    print("=" * 50)

def specific_exclusion_query(rag_chains):
    print("SPECIFIC EXCLUSION CRITERIA QUERY")
    print("=" * 50)
    print(rag_chains["rag_chain_1_chunk1000_overlap100"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_2_chunk1000_overlap200"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_3_chunk1000_overlap300"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_4_chunk1000_overlap400"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_5_chunk1000_overlap500"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_6_chunk2000_overlap100"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_7_chunk2000_overlap200"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_8_chunk2000_overlap300"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_9_chunk2000_overlap400"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)
    print(rag_chains["rag_chain_10_chunk2000_overlap500"]["chain"].invoke({"question": "What are the 4th and 7th exclusion criteria of the protocol?"}))
    print("=" * 50)